### ISSUE TITLE
[Vssue][Comment]留言板

### ISSUE THREAD

**Issue by eryajf** [eryajf/HowToStartOpenSource#14]
https://eryajf.github.io/HowToStartOpenSource/message-board/

**Comment by eryajf** [comment]
每篇文章都有独立的评论区，这里作为一个总的交流区，来到这里的朋友，可以畅所欲言🥳！

**Comment by SunSeekerX** [comment]
道理我都懂，为啥放一个这么好看的妹子？？？

**Comment by eryajf** [comment]
@SunSeekerX

> 道理我都懂，为啥放一个这么好看的妹子？？？

用以激发你在思考留言内容时的奇思妙想😬
PS：技术工作已经够累了，没事儿来留言区赏心悦目一下不好嘛🤣

**Comment by real-jiakai** [comment]
@SunSeekerX

> 道理我都懂，为啥放一个这么好看的妹子？？？

那妹子叫徐璐。刚搜图搜了一下。😂😂😂

**Comment by redgreat** [comment]
这评论字得颜色真是一言难尽~

**Comment by eryajf** [comment]
@redgreat

> 这评论字得颜色真是一言难尽~

评论区后端存储使用GitHub的Issue，看起来两者没什么差别，你说的颜色指的是哪里的问题呢

**Comment by redgreat** [comment]
> 

![image](https://user-images.githubusercontent.com/1754926/186295753-7ecb7e9b-9e07-4a68-b2ab-c4aed11ade2f.png)

**Comment by eryajf** [comment]
哦哦，这是跟你设置成黑色主题有关，我在白色主题下，没这么明显
<img width="906" alt="image" src="https://user-images.githubusercontent.com/33259379/186296619-a400dc5f-3609-4256-82c3-168ee8c20dba.png">
