### ISSUE TITLE
[Vssue][Comment]基础配置

### ISSUE THREAD

**Issue by eryajf** [eryajf/HowToStartOpenSource#2]
https://eryajf.github.io/HowToStartOpenSource/pages/24768e/

**Comment by Loveyless** [comment]
评论功能你怎么实现的 我看你挂的githubpage

**Comment by Loveyless** [comment]
我懂了 Vssue

**Comment by eryajf** [comment]
@Loveyless

> 我懂了 Vssue
> 

是的，用了一个非官方提供的插件[vuepress-plugin-vssue-global](https://github.com/u2sb/vuepress-plugin-vssue-global)，可通过如下方式安装该插件：

```
yarn add vuepress-plugin-vssue-global
```

剩下的配置参考此处：[配置评论](https://github.com/eryajf/vdoing-template#%E9%85%8D%E7%BD%AE%E8%AF%84%E8%AE%BA)

**Comment by Loveyless** [comment]
感谢感谢
