### ISSUE TITLE
[疑問]要求授權

### ISSUE THREAD

**Issue by EvanHsieh0415** [eryajf/HowToStartOpenSource#29]
請問為什麼當我點進線上版`06.issue与pr模板的配置及应用`時會被要求授權 內容為

>Repositories
>Public repositories
>
>This application will be able to read and write all public repository data. This includes the following:
>
>- Code
>- Issues
>- Pull requests
>- Wikis
>- Settings
>- Webhooks and services
>- Deploy keys

**Comment by eryajf** [comment]
如果单纯是阅读文档内容，按理说不应该会有这个授权，有一种可能大概是加载底部评论区，所以走到授权了，但是我这里并没有复现这个情况！

**Comment by EvanHsieh0415** [comment]
順便提一下，深色模式下留言區與每頁評論數的文字不易閱讀
![圖片](https://user-images.githubusercontent.com/74277414/193213691-ee3cdf3a-423e-49b1-a6e9-73ef1cedefab.png)

**Comment by EvanHsieh0415** [comment]
> 如果单纯是阅读文档内容，按理说不应该会有这个授权，有一种可能大概是加载底部评论区，所以走到授权了，但是我这里并没有复现这个情况！

我剛剛再開了一次，也復現不了:cry:

**Comment by eryajf** [comment]
> 深色模式下留言區與每頁評論數的文字不易閱讀

确实有这个问题，这是评论这个插件的显示问题，暂时我没有办法进行修复。

**Comment by EvanHsieh0415** [comment]
好的感謝

**Comment by EvanHsieh0415** [comment]
好的收到，感謝你的回覆

**Comment by eryajf** [comment]
> 好的收到，感謝你的回覆

不必客气，看到你属地台湾，有种莫名的好感，遥祝愉快！！
