### ISSUE TITLE
Image not loading in the documentation: BasicContent/HowtoConfigureApersonalGithubPage

### ISSUE THREAD

**Issue by ArslanYM** [eryajf/HowToStartOpenSource#41]
![issue](https://user-images.githubusercontent.com/104521101/221140717-b17f8a42-7a0f-4224-809c-5fba08d59a8d.png)

**Comment by eryajf** [comment]
This picture is relatively large. It may be because of the network on your side. It looks fine to me.

<img width="990" alt="image" src="https://user-images.githubusercontent.com/33259379/221147211-31b707ed-706e-477b-8758-ff94594554f4.png">

**Comment by ArslanYM** [comment]
Yeah youre right!
