### ISSUE TITLE
bug : auto scrolling is irritating

### ISSUE THREAD

**Issue by ArslanYM** [eryajf/HowToStartOpenSource#43]
when scrolling down to read the documentation , the page gets scrolled up automatically.
here: 
https://eryajf.github.io/HowToStartOpenSource/views/01-basic-content/05-How-to-configure-a-personal-GitHub-home-page-with-elegance-and-beauty.html#%E5%B1%95%E7%A4%BA****

**Comment by eryajf** [comment]
There is indeed this problem, I will take a look at it later when I have time

**Comment by Ansen** [comment]
same problem

![firefox_K1RsLDqa3J](https://github.com/eryajf/HowToStartOpenSource/assets/676412/d1174f75-4c8a-47cb-96ca-15207b6923cc)

**Comment by Chendaqian** [comment]
确实，要一直拖动

**Comment by eryajf** [comment]
十分抱歉，最近一直比较忙，等随后有空了，我折腾一下这个问题。

**Comment by eryajf** [comment]
目前升级到了v2，该问题已消失。
